import React, { useEffect, useRef } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import Draggable from 'react-draggable'

const Home: NextPage = () => {
  const letterFRef = useRef<any>()
  const logoLetterLRef = useRef<any>()
  const logoLetterURef = useRef<any>()

  useEffect(() => {
    if (letterFRef.current) {
      letterFRef.current.onanimationend = () => {
        logoLetterLRef.current?.classList.add('animate')
        setTimeout(() => {
          document.querySelectorAll('.letterL').forEach((element) => {
            element.classList.add('animate')
          })
        }, 150)
        setTimeout(() => {
          logoLetterURef.current?.classList.add('animate')
        }, 600)
        setTimeout(() => {
          document.querySelectorAll('.letterU').forEach((element) => {
            element.classList.add('animate')
          })
        }, 750)
      }
    }
  }, [])

  return (
    <>
      <Head>
        <title>PlanetScale Flux</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center justify-center h-screen bg-center bg-square-grid'>
        <Draggable grid={[106, 106]}>
          <div className='relative bg-white'>
            <svg
              width='318'
              height='102'
              viewBox='0 0 318 102'
              fill='none'
              xmlns='http://www.w3.org/2000/svg'
              className='text-gray-100'
            >
              <path
                d='M233.216 0C231.397 0 230.273 1.98508 231.209 3.5454L259.18 50.1639L231.209 96.7825C230.273 98.3428 231.397 100.328 233.216 100.328H257.286C258.461 100.328 259.55 99.7115 260.154 98.7042L274.229 75.2459L288.304 98.7042C288.909 99.7115 289.997 100.328 291.172 100.328H315.242C317.062 100.328 318.186 98.3428 317.249 96.7825L289.278 50.1639L317.249 3.5454C318.186 1.98508 317.062 0 315.242 0H291.172C289.997 0 288.909 0.616344 288.304 1.62365L274.229 25.082L260.154 1.62365C259.55 0.616344 258.461 0 257.286 0H233.216Z'
                fill='currentColor'
              />
            </svg>

            <div className='logo-letter absolute top-0 left-0 w-[70px] h-[100px]'>
              {/* F */}
              <div className='f1 bg-red-500 absolute bottom-0 left-0 w-[27px] h-[100px] rounded-[3px] transition-all'></div>
              <div className='f2 bg-red-500 absolute top-0 left-0 w-[70px] h-[27px] rounded-[3px]'></div>
              <div
                ref={letterFRef}
                className='f3 bg-red-500 absolute top-[47px] left-0 w-[53px] h-[27px] rounded-[3px]'
              ></div>
            </div>

            <div
              ref={logoLetterLRef}
              className='logo-letter logo-letter-L absolute top-0 left-[76px] w-[60px] h-[100px]'
            >
              {/* L */}
              <div className='letterL l1 bg-red-500 absolute top-0 left-0 w-[27px] h-[100px] rounded-[3px] transition-all'></div>
              <div className='letterL l2 bg-red-500 absolute bottom-0 left-0 w-[60px] h-[27px] rounded-[3px]'></div>
              <div className='letterL l3 bg-red-500 absolute bottom-0 left-0 w-[53px] h-[27px] rounded-[3px]'></div>
            </div>

            <div
              ref={logoLetterURef}
              className='logo-letter logo-letter-U absolute top-0 left-[142px] w-[84px] h-[101px]'
            >
              {/* L */}
              <div className='letterU u1 bg-red-500 absolute top-0 left-0 w-[27px] h-[62px] rounded-t-[3px] transition-all'></div>
              <div className='letterU u2 bg-red-500 absolute bottom-[39px] right-0 w-[27px] h-[62px] rounded-t-[3px]'></div>
              <div className='letterU u3 bg-red-500 absolute bottom-0 left-0 w-[84px] h-[40px] rounded-[3px] rounded-b-full'></div>
              <div className='letterU u4 hidden z-10 rounded-full w-[30px] h-[30px] bg-primary absolute bottom-[27px] left-[27px]'></div>
            </div>
          </div>
        </Draggable>
      </main>
    </>
  )
}

export default Home
