import type { NextPage } from 'next'
import Head from 'next/head'
import Div100vh from 'react-div-100vh'
import LogoAnimated from '../components/LogoAnimated'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Flux</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Div100vh>
        <main className='flex items-center justify-center h-full bg-center bg-square-grid'>
          <LogoAnimated />
        </main>
      </Div100vh>
    </>
  )
}

export default Home
