import type { NextPage } from 'next'
import Head from 'next/head'
import LogoAnimated from '../components/LogoAnimated'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Flux</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center justify-center h-screen bg-center bg-square-grid'>
        <LogoAnimated />
      </main>
    </>
  )
}

export default Home
